Table Major:

```sql
create table Major(MajorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, MajorName VARCHAR2(60));
```

Data Sample For Table Major:

```sql
INSERT ALL
into Subject(MajorID, MajorName) values ('1','Computer Science And Engineering')
into Subject(MajorID, MajorName) values ('2','Finance And Technology')
into Subject(MajorID, MajorName) values ('3','Business Information Technology')
into Subject(MajorID, MajorName) values ('4','International Relations')
into Subject(MajorID, MajorName) values ('5','Accounting')
into Subject(MajorID, MajorName) values ('6','Cybersecurity')
into Subject(MajorID, MajorName) values ('7','Data Science')
into Subject(MajorID, MajorName) values ('8','Interior Design')
into Subject(MajorID, MajorName) values ('9','International Business')
into Subject(MajorID, MajorName) values ('10','Economic')
into Subject(MajorID, MajorName) values ('11','Digital Arts')
Select * from dual;
//PK can be auto-generated
```

Table Subject:

```sql
Create table Subject(SubjectID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, SubjectName VARCHAR(60),
MajorID NUMBER, CONSTRAINT FK_MajorID Foreign Key (MajorID) references Major(MajorID) on delete cascade);
```

```sql
INSERT ALL
into Subject(SubjectID, SubjectName, MajorID) values ('1','Management Information System','1')
into Subject(SubjectID, SubjectName, MajorID) values ('2','Data Science','1')
into Subject(SubjectID, SubjectName, MajorID) values ('3','CyberSecurity','1')
into Subject(SubjectID, SubjectName, MajorID) values ('4','Computer Ethics','1')
into Subject(SubjectID, SubjectName, MajorID) values ('5','Software Testing','1')
Select * from dual;
//PK can be auto-generated
```

Table Student:

```sql
create table Student(StudentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, StudentName VARCHAR(70), Gender VARCHAR2(10),
MajorID NUMBER,
CONSTRAINT FK_MajorID_Student Foreign Key (MajorID) references Major(MajorID) on delete cascade,
DOB DATE NOT NULL,
POB VARCHAR2(70), PhoneNumber VARCHAR(15));
```

Data sample for Table Student:

```sql
INSERT ALL
into Student(StudentID, StudentName, Gender, MajorID, DOB, POB, PhoneNumber)
Values('1001', 'Vong Kaneka', 'Female', '1', TO_DATE('23-MAY-2003','DD-MON-YYYY'),'PHNOM PENH',' 085878676' ) 
into Student(StudentID, StudentName, Gender, MajorID, DOB, POB, PhoneNumber)
Values('1002', 'Mam Kimhouy', 'Female', '4', TO_DATE('24-MAY-2004','DD-MON-YYYY'),'PHNOM PENH','015888676') 
into Student(StudentID, StudentName, Gender, MajorID, DOB, POB, PhoneNumber)
Values('1003', 'Vong Sovanreach', 'Male', '3', TO_DATE('05-NOV-2007','DD-MON-YYYY'),'PHNOM PENH','077510210') 
into Student(StudentID, StudentName, Gender, MajorID, DOB, POB, PhoneNumber)
Values('1004', 'Thri ChingSien', 'Female', '2', TO_DATE('13-DEC-2004','DD-MON-YYYY'),'PHNOM PENH','012399296') 
into Student(StudentID, StudentName, Gender, MajorID, DOB, POB, PhoneNumber)
Values('1005', 'Cheung VeyChheang', 'Male', '5', TO_DATE('08-MAR-2005','DD-MON-YYYY'),'PHNOM PENH','089399296')
select * from dual;
//PK can be auto-generated
```

table scores:

```sql
Create Table Scores(ScoreID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, StudentID NUMBER, SubjectID NUMBER, Score NUMBER(5,2),
CONSTRAINT chk_score_range CHECK (score >= 0 AND score <= 100)
);

```

data sample for table scores:

```sql
Insert ALL
into Scores(ScoreID, StudentID, SubjectID, Score) values ('1','1002','1',97.50)
into Scores(ScoreID, StudentID, SubjectID, Score) values ('2','1002','2',97.50)
into Scores(ScoreID, StudentID, SubjectID, Score) values ('3','1002','3',97.50) 
into Scores(ScoreID, StudentID, SubjectID, Score) values ('4','1002','4',97.50) 
into Scores(ScoreID, StudentID, SubjectID, Score) values ('5','1002','5',97.50) 
select * from dual;
//PK can be auto-generated
```

```sql
select * from Major;
select * from Subject;
select * from Student;
select * from Scores;

//JoinStudentAndScore
SELECT 
    st.StudentID, 
    st.StudentName, 
    su.SubjectName AS Subject, 
    sc.score       AS Score
FROM 
    Student st 
JOIN 
    Scores sc ON st.StudentID = sc.studentid
JOIN 
    Subject su ON sc.subjectid = su.SubjectID
WHERE 
    st.StudentID = 4586;
    
//Funct to calculate Total Score and Overall Grade
SELECT
    st.StudentID,
    st.StudentName,
    COUNT(sc.score) AS TotalSubjects,
    SUM(sc.score) AS TotalScores,
    ROUND(AVG(sc.score), 2) AS Average,
    ROUND(AVG((sc.score) / 100) * 5, 2) AS GPA
FROM 
    Student st 
JOIN 
    Scores sc ON st.StudentID = sc.studentid
GROUP BY 
    st.StudentID, st.StudentName;
```
